### ISSUE TITLE
How-to execute swing-back

### ISSUE THREAD

**Issue by sjalloul** [sbtqa/swing-back#10]
Hi there,

I hope this finds you well.  I am exploring tools with the mindset of being able to expand on this framework, and like the possibility to use page object/cucumber to author tests.  Can you clarify, how does one get started? I tried following some of the documentation, but running into setup issues.

Best, 
Sam

**Comment by clicman** [comment]
Hi, Sam!
Could you clarify issue what you’ve faced?
Are you need to test swing apps only or the web/mobile/rest?

Отправлено с iPhone

**Comment by sjalloul** [comment]
Zdravstvuyte Viktor,

I want to use it for a thick swing based application to interact from a functional perspective. In essence, perform some test of GUI in a similar fashion as running tests against a web or mobile application. 

I followed the instructions for the following [swingback-test ](https://github.com/sbtqa/swingback-test), but don't see the application/or test executing against the sample application 'SwingApplication.java'. Just wanted to get some input on what additional steps are missing from my understanding in order to execute. Any help would be appreciated!

Sam

**Comment by clicman** [comment]
Okay. I will create the test app on next week and will commit out of the box test example. Stay tuned!

**Comment by clicman** [comment]
Hi! I've updated https://github.com/sbtqa/swingback-test
try to pull the latest master and run CucumberTest

**Comment by sjalloul** [comment]
Thanks for making the changes to the project.  I was able to execute the cucumber script but the behavior of clicking on the application is from a user input.  I was under the impression this proposed work helps in automating interaction with GUI and performing the actions i.e. clicks, selection...etc.

**Comment by clicman** [comment]
So... Does it solves your problem?

**Comment by sjalloul** [comment]
I am afraid it doesn't. I was looking for an alternative to [Robot framework](https://github.com/robotframework/SwingLibrary) while staying in pure java.  I am only saying, that because you do use Jemmy lib -- if I may ask, what was the intent of this project?

**Comment by clicman** [comment]
Jemmy is the best swing ui a testing library. 
Swing back works on jemmy over test automation framework with cucumber JVM inside. 
The main benefit- is page object pattern and out of the box cucumber step definitions.
